c-cube/qcheck

example/QCheck_ounit_test.ml
src/QCheck.ml
src/QCheck.mli
src/QCheck_runner.ml

This patch record the backtraces of exceptions raised during a test, so that it can be printed afterward.
Consider the following file foo.ml:
```ocaml
exception Error
let f i =
raise Error
let test = QCheck.(Test.make int f)
let () =
QCheck_runner.run_tests_main [test]
```
Once compiled the results are the following.
Before patch:
```
$ OCAMLRUNPARAM=b ./foo.native 
random seed: 133695414
test `anon_test_1` raised exception `Foo.Error`
on `0 (after 62 shrink steps)`
failure (1 tests failed, ran 1 tests)
```
After patch:
```
$ OCAMLRUNPARAM=b ./foo.native 
random seed: 502100165
test `anon_test_1` raised exception `Foo.Error`
on `0 (after 61 shrink steps)`
Raised at file "foo.ml", line 5, characters 8-13
Called from file "src/QCheck.ml", line 844, characters 13-33
failure (1 tests failed, …
```

Better handling of backtraces

---

src/QCheck.ml
src/QCheck.mli

Accessing the number of tests to run would be interesting for writing `step` functions.

Add Test.get_count on test cells

---

example/QCheck_runner_test.ml
src/QCheck_runner.ml
src/QCheck_runner.mli

The previous implementation assumed a maximum size of 4 for integer printing of integers in order to keep a correct alignment of columns. This pull request dynamically computes the required size for printing integers so that everything lines up nicely.
The number of test instances and long factors in `example/QCheck_runner_test.ml` have been updated to test different sizes.
Examples of previous outputs:
```
generated  error;  fail; pass / total       time -- test name
[✓] ( 100)    0 ;    0 ;  100 /  100 --     0.1s -- list_rev_is_involutive
[✗] (   2)    0 ;    1 ;    1 /   10 --     0.0s -- should_fail_sort_id
[✗] (   1)    1 ;    0 ;    0 /   10 --     0.0s -- should_error_raise_exn
[✓] ( 100)    0 ;    0 ;  100 /  100 --     0.0s -- collect_results
```
```
generated  error;  fail; …
```

Adjust integer size printing in qcheck_runner

---

src/QCheck.ml

This is an attempt at lifting the 2^30 restriction of PR #7 to something bigger on 64-bit machines.
It works by reusing `pint` which already handles the uniform glueing of 30-bit chunks.
Limitation: it should work up to `max_int` (2^62 on my 64-bit machine) as argument to `Gen.int_bound`.
But it is limited to intervals of length `max_int` as arguments to `Gen.int_range`. 
As a consequence generating test input with `Gen.int_range 0 max_int` and `Gen.int_range min_int (-1)` works, but `Gen.int_range (-1) max_int` and `Gen.int_range min_int 0` will fail as these intervals are just one greater than `max_int` in length.
Is it uniform?
Since `pint` is already supposed to provide uniform bit-patterns, and `Gen.int_range` just calls `Gen.int_bound` it is a question of whether `Gen.int_bound` …

Change Gen.int_bount/int_range to support up to 2^62 / max_int

---

src/QCheck.ml
src/QCheck.mli

Cleanup #28 to still raise `Invalid_arg` on illegal arguments (as the API doc promises).
Also update the .mli file to reflect the loosened restrictions.

Change asserts to raise Invalid_arg (following the doc), and update doc

---

src/QCheck.ml
src/QCheck.mli
src/QCheck_runner.ml

Following comments in issue #33, this pull request make the verbose mode a bit better. The modifications made are:
- Add colors to the checkmarks printed to the left
- Print the status line of a test before it begin (compared to previsouly where it would only be printed after the first instance had been tested)
- Add a notion of event to `QCheck.Test.check_cell`, to represent intermediary events during the testing of an instance
- Use the event handler to print the current status of a test (either generating a an instance, collecting statistics about that instance, testing the law on the instance, or shrinking an instance)
For people interested in seeing the new features in action, I found that using the seed `80394201` makes the `fold_left fold_right uncurried` test take about 3s on my …

Better progress feedback in verbose mode

---

src/QCheck_runner.ml
src/QCheck_runner.mli

In my tests, the `time_between_msg` float ref has resulted in only the `(collecting)` messages being printed and never others such as `generating`.
More generally, a non-zero value will always prevent the first `(generating)` message from being printed since the `step` printing function should not really take a lot of time. Also, assuming generation is reasonably fast but testing takes some time (which is the typical case I assume), `(collecting)` has an overwhelming chance of being the one and only phase being printed, since it is the first phase after testing: indeed, assume the step function (or the last `collection`) has been printed at time `t`, then assuming the printing is fast (or there is nothing to collect), then the generation message will be prevented since it occurs at `t + …

Allow setting time_between_msg in runner

---

src/core/QCheck.ml
src/core/QCheck.mli

See the discussion in #68 -- I think that this PR should supersed #68.
> I'm not sure what is best, but my conclusion for now is that a generic `Iter` combinator (at this level I think my implementation is the right/canonical one) has a behavior that is not optimal for the use-case (shrinking a list of values), so this PR is maybe not the best idea. We should rather provide a function in the `Shrink` module, that does something better than the current `Shrink.list`.
>
> Ideally we would have `Shrink.list_spine : 'a list t` and `Shrink.list_elems : 'a t -> 'a list t`, the first one only drops elements of the input and the second only shrinks elements of the input, and then `Shrink.list` is just `compose Shrink.list_spine (Shrink.list_elems ~shrink)`.
I was a bit surprised to find out that …

Shrink: decompose Shrink.list into Shrink.list_spine and Shrink.list_elems

---

src/core/QCheck.ml
src/core/QCheck.mli

- add `float_bound_inclusive`, `float_bound_exclusive` generators to generate floats between 0 and given bound (proposed by @gasche)
- add `float_range` to generate floats in the given range (solves #58)
- fix minor indentation inconsistency
Note: QCheck has own float generation algorithm, while I used `Random.State.float` for simplicity.

Add float generators with bound and range

---

src/core/QCheck.ml
src/core/QCheck.mli

Adds a function `shuffle_w_l`, which creates a generator that can shuffle the given list according to the elements' weights.

add weighted shuffled lists generator

---

src/core/QCheck.ml
src/core/QCheck.mli

Together with @gasche, we were implementing our own `Gen.frequency` looking at the implementation by QCheck. 
We saw that to generate a bounded int, it uses `Random.State.int` instead of `int_bound`. As we wanted to have the same values generated by both `Gen.frequency` and our implementation, we also opted for using `Random.State.int`; however, it would be better if we used the API provided by QCheck instead of a lower-level library fn. 
After this change, `int_bound` and `Random.State.int` will generate same values for `bound < 2^{30}` with own implementation for larger values, which would satisfy most of the users, assumably. 
(@gasche can probably phrase it more convincingly if necessary)

Change implementation of 'int_bound'

---

src/core/QCheck.ml
src/core/QCheck.mli

When I changed `int_bound` to use `Random.State.int` (`RS.int`), I did not take into consideration that `int_bound` generates values including `bound`, while `RS.int` doesn't. 
This PR fixes that omission. (It also changes the max bound for using `RS.int` from `2^{30}-1` to `2^{30}-2`, so that we can pass `bound+1` to `RS.int` without int representation problems on 32-bit machines.

fix 'int_bound' bound inclusiveness problem

---

src/core/QCheck.ml

I just got bitten by a little embarrasing issue:
The reworked list shrinker fails to shrink a one-element list! 😮
```
utop # Shrink.list [0] (fun is -> Printf.printf "%s\n" (Print.list Print.int is));;
- : unit = ()
```
The problem is the `chunk_size` computed as `n/2` which is `0` over `int` when `n` is `1`.
Simply adding one before halving fixes it, and will generally increment the `chunk_size` for any odd-length counterexample. For example, here are the shrinking steps of a 35-element list:
```ocaml
utop # Random.init 123456;;
- : unit = ()
─( 14:35:49 )─< command 24 >─────────────────────────────────────────────────────────────────────────────────────────{ counter: 0 }─
utop # let print_list xs = print_endline (Print.list Print.int xs) in
Test.check_exn ~rand:(Random.get_state ()) …
```

Fix singleton list shrinking

---

Makefile
src/runner/QCheck_base_runner.ml
src/runner/QCheck_base_runner.mli

Should fix  #71 
cc @gasche , sorry for the delay.

Add debug shrinking log

---

src/core/QCheck.ml
src/core/QCheck.mli

This is addressing #82.
It just copies the `int` shrinking strategy. Potentially we could factor out the general strategy and parameterize all three integer shrinkers over this common core. For now I chose to keep them very similar and right next to each other.
It seems to work fine:
```
val t : Test.t = QCheck.Test.Test <abstr>
generated error fail pass / total     time test name
[✗]    1    0    1    0 /  100     0.0s anon_test_3
--- Failure --------------------------------------------------------------------
Test anon_test_3 failed (14 shrink steps):
2343544l
================================================================================
failure (1 tests failed, 0 tests errored, ran 1 tests)
- : int = 1
generated error fail pass / total     time test name
[✗]    1    0    1    0 / …
```

Int shrinkers

---

src/runner/QCheck_base_runner.ml

This addresses #85.
Rather than print a separator and two headers for each stat, this prints one separator per test that names it and then a single header for each stat.
Compare the following output to #85:
```ocaml
val t : int arbitrary -> string -> Test.t = <fun>
random seed: 466141584
generated error fail pass / total     time test name
[✓]  100    0    0  100 /  100     0.0s small_int dist
[✓]  100    0    0  100 /  100     0.0s int dist
+++ Stats for small_int dist ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
stats mod10:
num: 100, avg: 5.02, stddev: 2.58, median 5, min 0, max 9
0: ##################                                                5
1: ######################                                            6
2: ######################################## …
```

less newline-verbose stats

---

src/core/QCheck.ml
src/core/QCheck.mli

The new version first checks if the given intertval has a constant sign, in which case its range is smaller than `max_int`.
Otherwise, it splits it to have two constant intervals and then chooses uniforml (i.e. according to their size ratios computed in float) the one in which he branches to `int_bound`

modify int_range to make it accept ranges bigger than max_int.

---

src/core/QCheck.ml
src/core/QCheck.mli

The goal of this PR is to implement a function that takes a natural number `n` and parameter `k`, and uniformly splits `n` into `k` numbers `n1..nk` that sum back to `n` (`n1 + ... +nk = n`). This is useful when splitting "fuel" or "size" in a random generator, among `k` components instead of just two. (cc @olivier-martinot, with whom I am collaborating on a random generator that would benefit.)
Two variants are provided: in `nat_split`, the `n1..nk` are natural numbers (range `[0;n]`), in `pos_split` they are strictly positive (range `[1;n]`, or in fact `[1;n-k]`).
The code for these functions is simple and relies on a generic helper that is also useful. However getting them right is tricky, and random generators are hard to test. I checked the implementation in an experimental version …

`nat_split`, `pos_split`

---

src/core/QCheck.mli
src/core/QCheck2.ml
src/core/QCheck2.mli
src/runner/QCheck_base_runner.ml

`'a arbitrary` is totally removed.
There is still TODOs inside the code, some can be fixed either by me but I need to fetch some information or
you can suggest the changes (it's mainly documentation).
print, stats and collect are inside `'a cell`:
```ocaml
type 'a cell = {
count : int; (* number of tests to do *)
long_factor : int; (* multiplicative factor for long test count *)
max_gen : int; (* max number of instances to generate (>= count) *)
max_fail : int; (* max number of failures *)
law : 'a -> bool; (* the law to check *)
gen : 'a Gen.t; (* how to generate/shrink instances *)
print : 'a Print.t option; (* how to print values *)
collect : ('a -> string) option; (* /!\ TODO: collect ? *)
stats : 'a stat list; (* distribution of values of type 'a *)
qcheck1_shrink : ('a -> ('a -> …
```

Remove arbitrary from QCheck2

---

src/core/QCheck2.ml
test/core/test.ml

* Fix bug in bytes/string shrinking (bad laziness + ref)
* Add test to prevent reintroducing this bug in the future
Closes https://github.com/c-cube/qcheck/issues/135
The added test fails (stackoverflow) on `master` but succeeds with the fix.

fix (bytes): Fix bytes shrinking

---

example/alcotest/dune
example/alcotest/run_alcotest.sh
example/dune
example/ounit/dune
example/ounit/run_ounit.sh

This is an attempt to lift the `< 4.09` requirement on @c-cube's expect tests.
It works by just omitting `file` from the `grep`ed error string. It has been verified on 4.11.2 and 4.12 locally,
I've furthermore tested the change by making a dummy modification in the `output.txt,expected`-files and verified that any such difference is caught and reported.
Motivation: I wanted to add some more (negative) expect tests of QCheck2(+1) and test that they run locally with 4.12.

Lift 4.09 restriction on expect tests

---

src/core/QCheck2.ml
test/core/dune

This fixes a rare overflow in the histogram labels (and simplifies a couple of other things).
Before (notice the negative labels on the last bucket):
```ocaml
utop # #require "qcheck";;
utop # open QCheck;;
utop # let t = Test.make ~count:1_000 (add_stat ("dist",fun x -> x) (oneof [small_int_corners ();int])) (fun _ -> true);;
val t : Test.t = QCheck.Test.Test <abstr>
utop # QCheck_runner.run_tests ~verbose:true [t];;
random seed: 153870556
generated error fail pass / total     time test name
[✓] 1000    0    0 1000 / 1000     0.0s anon_test_1
+++ Stats for anon_test_1 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
stats dist:
num: 1000, avg: -55083208105414400.00, stddev: 1847115855773139200.00, median 9, min -4590718933436425025, max 4611686018427387903 …
```

Stat overflow

---

example/alcotest/dune
example/dune
example/ounit/dune
src/dune
src/ounit/dune

Fix all instance of `dune runtest -p qcheck*` encountered when testing through opam (see https://github.com/ocaml/opam-repository/pull/19207)

Fix the tests and remove out of place (optional)

---

src/core/QCheck2.ml
test/core/QCheck2_expect_test.ml
test/core/QCheck_expect_test.ml
test/core/qcheck2_output.txt.expected
test/core/qcheck_output.txt.expected

This PR addresses issue #156. It 
- replaces `QCheck2.gen.list_size` with a tail-recursive generator over `Tree.t` similar to @sir4ur0n's suggestion
- updates the expected test outputs
- removes the custom length printer from the `list_equal_dupl` test (to ensure that both counterexamples are `[0]`)

Fix `QCheck2.gen.list_size Stack overflow`

---

src/core/QCheck.ml
src/core/QCheck.mli
test/core/QCheck_expect_test.ml
test/core/qcheck_output.txt.expected

This is a fix for several bugs reported in #180.
Those functions (and `range_subset`), implemented by myself in #114, were utter garbage. I had tested their implementation heavily within a different random library, and when I ported them to QCheck it seems that I messed things up considerably (this is fiddly code full of off-by-one traps etc.).
In the present PR I have gone over the implementation of each function and done some manual testing, and I also wrote automated tests in the existing QCheck testsuite. (This forced me to think about the valid input space for the combinators; I extended `pos_split` to support the case `size=0, n=0`, and found a treacherous bug when `size=1`.)
My recommendation for the future would be to encourage new generators to come with their tests.
Sorry for …

fix Gen.{nat,pos}_split{2,}

---

example/alcotest/output.txt.expected
example/alcotest/run_alcotest.sh

This contains the fix proposed in #193.
I have checked that it is OK locally with Alcotest 1.3.0, 1.4.0, 1.5.0. YMMV 🙃

CI fix for Alcotest whitespace changes

---

src/ppx_deriving_qcheck/ppx_deriving_qcheck.ml
test/ppx_deriving_qcheck/deriver/dune
test/ppx_deriving_qcheck/deriver/test_qualified_names.ml

Qualified type are currently concatenated into a unique identifier, so it becomes a constructor:
```ocaml
module Q = struct
type t = int
[@@deriving qcheck]
end
type t = Q.t
[@@deriving qcheck]
```
```
dune runtest
File "test/ppx_deriving_qcheck/deriver/test_qualified_names.ml", lines 6-7, characters 0-20:
6 | type t = Q.t
7 |  [@@deriving qcheck]
Error: Unbound constructor Q.gen
```
I added the test outside `test.ml`because string comparison doesn't show the difference (`let gen = Q.gen` in both case). I tried to see if the bug was obvious but I haven't found anything.

Add regression tests for qualified type

---

CHANGELOG.md
src/core/QCheck.ml
src/core/QCheck.mli
src/core/QCheck2.ml
src/core/QCheck2.mli
test/core/QCheck2_expect_test.ml
test/core/QCheck_expect_test.ml
test/core/qcheck2_output.txt.expected
test/core/qcheck_output.txt.expected

Alternative (and easy) solution for #108.
Nothing smart happening there.

Add tup2 to tup9 for Gen

---

src/ppx_deriving_qcheck/README.md
src/ppx_deriving_qcheck/ppx_deriving_qcheck.ml
test/ppx_deriving_qcheck/deriver/test.ml

Fixes #187 
Before this MR:
```ocaml
type tree = [ `Leaf of int | `Node of tree * tree ]
[@@deriving qcheck]
let gen_tree =
(QCheck.Gen.frequency
[(1, (QCheck.Gen.map (fun gen0 -> `Leaf gen0) QCheck.Gen.int));
(1,
(QCheck.Gen.map (fun gen0 -> `Node gen0)
(QCheck.Gen.map (fun (gen0, gen1) -> (gen0, gen1))
(QCheck.Gen.pair gen_tree gen_tree))))] : tree QCheck.Gen.t)
```
With this MR:
```ocaml
type tree = [ `Leaf of int | `Node of tree * tree ]
[@@deriving qcheck]
let gen_tree =
(QCheck.Gen.sized @@ QCheck.Gen.fix (fun self -> function
| 0 -> QCheck.Gen.frequency [(1, QCheck.Gen.map (fun gen0 -> `Leaf gen0) QCheck.Gen.int)]
| n -> QCheck.Gen.frequency [
( 1, QCheck.Gen.map` (fun gen0 -> `Leaf gen0) QCheck.Gen.int );
( 1,
QCheck.Gen.map
(fun gen0 -> `Node gen0)
(QCheck.Gen.map
(fun (gen0, …
```

Deriver: fix recursive poly variants derivation

---

src/ppx_deriving_qcheck/QCheck_generators.ml
src/ppx_deriving_qcheck/ppx_deriving_qcheck.ml
test/ppx_deriving_qcheck/deriver/dune
test/ppx_deriving_qcheck/deriver/helpers.ml
test/ppx_deriving_qcheck/deriver/test_primitives.ml
test/ppx_deriving_qcheck/deriver/test_qualified_names.ml
test/ppx_deriving_qcheck/deriver/test_record.ml
test/ppx_deriving_qcheck/deriver/test_recursive.ml
test/ppx_deriving_qcheck/deriver/test_textual.ml
test/ppx_deriving_qcheck/deriver/test_tuple.ml
test/ppx_deriving_qcheck/deriver/test_variants.ml

I think #201 raised an issue: textual diff tests are not enough (thank you @bobot)
Therefore, I started writing tests using the derived generators, we can then ensure both:
- The deriver produce a well-typed generator (at least for the types tested)
- The deriver uses the same generators as in QCheck
Thank to these tests, I found little bugs in the code, fixed alongside the tests.
~(Do not mind extra commits, it is for now rebased on #195, If someone review this before the merge of #195, you should
review commit by commit starting 7bf423be7e5a5206636608fb828b850b78904657)~

Deriver: more tests and some fixes

---

src/ppx_deriving_qcheck/ppx_deriving_qcheck.ml
test/ppx_deriving_qcheck/deriver/test_textual.ml

This fixes #213 (and adds a regression test for it) with the simple patch discussed in the issue.

Deriver fix unused var error

---

Makefile

On my machine, the test output would previously be garbled in various
ways. For example:
Done: 230/237 (jobs: 5)Testing `Test_Primitives'.
This run has ID `O6P0L2KW'.
[OK]          Primitives          0   test_int.
[OK]          Primitives          1   test_unit.
[OK]          Primitives          2   test_string.
[OK]          Primitives          3   test_char.
[OK]          Primitives          4   test_bool.
[OK]          Primitives          5   test_float.
[OK]          Primitives          6   test_int32.
[OK]          Primitives          7   test_int64.
[OK]          Primitives          8   test_option.
[OK]          Primitives          9   test_array.
...           Primitives         10   test_list.Testing `Test_Qualified_names'.
This run has ID `G59X8MGJ'.
[OK]          Qualified …

make test: remove the --no-buffer option

---

src/core/QCheck.mli
src/core/QCheck2.ml
src/core/QCheck2.mli

The parameter ?handler was added late to check_cell, and is missing
from its check_cell_exn counterpart for no good reason.
I hit this discrepancy when trying to debug a shrinker from within a Qcheck_alcotest test.

add ?handler parameter to check_cell_exn

---

example/alcotest/QCheck_alcotest_test.ml
example/alcotest/output.txt.expected
example/alcotest/run_alcotest.sh
src/alcotest/QCheck_alcotest.ml
src/alcotest/QCheck_alcotest.mli
src/runner/QCheck_base_runner.ml
src/runner/QCheck_base_runner.mli

This PR sits on top of #216; it implements a `debug_shrink` option for `QCheck_alcotest.to_alcotest`, allowing QCheck_alcotest users to debug their shrinkers.
I would consider this an important feature for QCheck_alcotest users: it's not possible in practice to develop your own shrinkers if you cannot debug the shrinker.

Alcotest: debug_shrink

---

src/ppx_deriving_qcheck/ppx_deriving_qcheck.ml
test/ppx_deriving_qcheck/deriver/test_textual.ml

#Closes #213 _again_
@jmid I went for your first option:
> I suppose it could be solved by writing a simple occurs n search (unless there is an easier way in ppxlib to check whether an identifier n occurs in a sub-expression) - and simply name it _n if it doesn't occur
I think it's pretty easy to do this kind of stuff with an `Ast_traverse`, some of the code could be refactored used this object (e.g. `is_recursive`).

Remove n fuel when its not used

---

src/core/QCheck.mli

I find the current document unclear about whether the upper bound is included or excluded for `Gen.int_bound` and `Gen.int_range`, especially since the behavior is not the same as `Random.int`. I propose to make very explicit.

Clarify upper bound inclusion in int Gen functions

---

src/core/QCheck2.mli

This is the first PR cherry-picking commits from #172, #174, and #176 sans all the shrink-logging noise.
The PR fixes typos in the exception documentation.

Fix exception documentation

---

test/core/QCheck2_expect_test.expected
test/core/QCheck2_tests.ml
test/core/QCheck_expect_test.expected
test/core/QCheck_tests.ml

This is a purely administrative PR that simply reorders a bunch of QCheck/QCheck2 tests to keep them and their order in sync.
It also removes a confusing comment about using `Test.make` without a `~shrink`-parameter:
`Test.make` does not accept a `~shrink` parameter.
Finally it corrects a typo in a test name.

Chore: Align expect test suites by reordering

---

test/core/dune
test/core/shrink_benchmark.ml

This PR adds a shrinker benchmark.
It iterates the (factored) shrinker tests in QCheck_tests.ml and QCheck2_tests.ml in pairs.
For each such pair of tests we measure
- time in seconds, denoted `Q1/s` and `Q2/s`
- the number of succesful shrinks, denoted `#succ`
- the number of shrink attempts, denoted `#att`
This is iterated across several seeds to make sure observations hold across more than one random run.
Finally we add up the timings to spot general trends.
Overall, the benchmark gives a reasonable idea of the state of affairs (see output below):
- the QCheck list shrinker tries *way* too many candidates, often making it unbearably inefficient on large lists, e.g, spending 9.8 secs over 5 milion shrink attempts of which only 1.696 are successful(!)
- the QCheck string shrinker does …

Shrinker performance benchmark

---

CHANGELOG.md
src/core/QCheck2.ml
src/core/QCheck2.mli
test/core/QCheck2_unit_tests.ml
test/core/QCheck_unit_tests.ml

In https://github.com/c-cube/qcheck/pull/142 we introduced a `QCHECK_COUNT` environment variable. It is very useful to debug flaky tests by running a dedicated pipeline with a lot higher `QCHECK_COUNT`. We decided that the `~count` in a `Test.make` overrides the environment variable (which I think is fine), but, there is no easy way to conditionally increase these given counts.
I propose another environment variable `QCHECK_COUNT_MULTIPLIER` to increase the `~count` value.

QCHECK_LONG_FACTOR environment variable

---

test/core/shrink_benchmark.ml

This little PR gives a more informative error message when the `shrink_benchmark` finds mismatching test names before running what we hope are corresponding lists of Shrink tests.

More informative error message in shrink_benchmark

---

CHANGELOG.md
example/QCheck_runner_test.ml
example/alcotest/QCheck_alcotest_test.ml
example/alcotest/output.txt.expected
example/ounit/QCheck_ounit_test.ml
example/ounit/QCheck_test.ml
example/ounit/output.txt.expected
example/output.txt.expected
src/alcotest/QCheck_alcotest.ml
src/core/QCheck.ml
src/core/QCheck.mli
src/core/QCheck2.ml
src/core/QCheck2.mli
src/ounit/QCheck_ounit.ml
src/runner/QCheck_base_runner.ml
test/core/QCheck2_expect_test.expected
test/core/QCheck2_tests.ml
test/core/QCheck_expect_test.expected
test/core/QCheck_tests.ml

This PR adds a "primitive" `Test.make_neg` which lets one express negative property-based tests, that is, tests that are supposed to fail. This can be useful
- to safe guard the error-finding ability of a generator
- to supplement existing positive test (supposed to succeed)
- to document in test source code which tests are supposed to fail and succeed
The commercial Erlang QuickCheck has a similar operation, `fails`: http://quviq.com/documentation/eqc/eqc.html#fails-1
Here's an example:
```ocaml
open QCheck
let t1 = Test.make_neg ~name:"all ints are even" small_int (fun i -> i mod 2 = 0)
let t2 = Test.make ~name:"int double" small_int (fun i -> i + i = i * 2)
let t2' = Test.make_neg ~name:"int double" small_int (fun i -> i + i = i * 2)
let t3 = Test.make_neg ~name:"list rev concat" (pair …
```

Add `Test.make_neg`

---

CHANGELOG.md
src/core/QCheck.ml
src/core/QCheck2.ml

Polymorphic equality is ill-defined regarding `nan`. This PR proposes to use `Float.equal` instead. The rational being that a test failling because `nan <> nan` is not very informative w.r.t the tested program.

use Float.equal

---

CHANGELOG.md
src/core/QCheck.ml
src/core/QCheck.mli

This PR is an attempt to fix #257.
It does so by:
- adding an optional argument to `Shrink.string` for character shrinking, with a conservative default
- fix character shrinkers in `QCheck.{printable_string,printable_string_of_size,small_printable_string,numeral_string,numeral_string_of_size}` so that they have the expected behaviour.
For now, we don't expose a `string arbitrary` that takes a shrinker as argument. Albeit it would be nice, there is the question of how to do it. I see three possibilities:
1. add an optional argument to `QCheck.string_gen` and `QCheck.string_gen_of_size`
2. add a non-optional argument to `QCheck.string_gen` and `QCheck.string_gen_of_size`
3. add two functions: `QCheck.string_gen_shrink` and `QCheck.string_gen_shrink_of_size`

parametirize string shrinker with a char shrinker

---

CHANGELOG.md
src/runner/QCheck_base_runner.ml

This PR adds an environment variable `QCHECK_MSG_INTERVAL` to control `QCheck_base_runner.time_between_msg`.
This feature is useful in a CI context, where updates are printed on consecutive lines and we want to avoid overflowing the CI log files with too many output lines.

Add QCHECK_MSG_INTERVAL environment variable

---

CHANGELOG.md
src/runner/QCheck_base_runner.ml

While switching from `dune exec path/some.exe -- -v -s 123` to `_build/default/path/some.exe` I mistakingly passed `--` which is not a valid QCheck option and was surprised by this error message:
```
_build/default/path/some.exe: unknown option '--'.
run qtest suite
-v                   
--verbose            enable verbose tests
--colors             colored output
[...]
```
This PR therefore changes the second line to
```
run QCheck test suite
```

Fix "unknown option" error message from runner

---

.github/workflows/main.yml
example/alcotest/dune

Opening #274 I realized the CI was triggered, because of our change from `master` to `main`.
This little PR updates the workflow accordingly, and also adjusts it to test 4.14 and the actual 5.0.0 release.

Update GitHub actions

---

CHANGELOG.md
example/alcotest/output.txt.expected.32
example/alcotest/output.txt.expected.64
example/alcotest/output.txt.expected.ocaml5
src/alcotest/QCheck_alcotest.ml
src/core/QCheck.mli
src/core/QCheck2.ml
src/core/QCheck2.mli
src/ounit/QCheck_ounit.ml
test/core/QCheck2_unit_tests.ml
test/core/QCheck_unit_tests.ml

Motivation for this PR:
https://github.com/c-cube/qcheck/pull/244#issuecomment-1423824479:
> I was just trying out the library and after seeing [this](https://c-cube.github.io/qcheck/0.20/qcheck-core/QCheck/index.html#tests):
>
> - [Test.make](https://c-cube.github.io/qcheck/0.20/qcheck-core/QCheck/Test/index.html#val-make) to build a test,
>  - [Test.make_neg](https://c-cube.github.io/qcheck/0.20/qcheck-core/QCheck/Test/index.html#val-make_neg) to build a negative test that is expected not to satisfy the tested property,
>   - [Test.check_exn](https://c-cube.github.io/qcheck/0.20/qcheck-core/QCheck/Test/index.html#val-check_exn) to run a single test with a simple runner.
>
> I started to try with some example of my own and I saw that `Test.check_exn` was doing the same for `make` and …

Make `Test.check_exn` honor test polarity

---

CHANGELOG.md
src/ppx_deriving_qcheck/ppx_deriving_qcheck.ml
test/ppx_deriving_qcheck/deriver/qcheck/test_textual.ml

This is an attempt at fixing #269.
With the fix in 3c1f147 we are able to derive a straight-forward, type-correct generator for `type t = Foo of t list` (yay!)
```ocaml
let rec gen_sized n =
QCheck.Gen.map (fun gen0 -> Foo gen0) (QCheck.Gen.list (gen_sized (n / 2)));;
let gen = QCheck.Gen.sized gen_sized
```
which blows the stack (less yay):
```
Stack overflow during evaluation (looping recursion?).
```
I think this is to be expected from the current simple, but predictable approach.
It could potentially be improved if we incorporate passing sizing explicitly to the derived `list` generator and thus try to reach a base-case that way.
While fixing this I noticed there was also a problem with record declarations in `is_rec_constr_decl`.
With the fix in daa357e for that, one can derive a …

Fix is_rec_typ deriver bug(s)

---

README.adoc

Fixes this error with asciidoc 10.2.0 (and fixes incorrect output as well):
```
$ asciidoc README.adoc 
asciidoc: ERROR: README.adoc: line 411: illegal style name: @@deriving qcheck
```

Fix asciidoc error

---

CHANGELOG.md
qcheck-alcotest.opam
qcheck-core.opam
qcheck-ounit.opam
qcheck.opam
src/alcotest/dune
src/core/dune
src/ounit/dune

If I understand correctly, the `bytes` dependency is really only useful to support older versions of OCaml (before 4.02), but QCheck requires at least 4.08 anyway.
So this PR proposes to drop that dependency altogether.
To give this a bit more context, this PR comes from wanting to run some tests that use QCheck core in a CI setup where Opam is not an option (yet). So this is working by vendoring QCheck and relying on dune’s modularity. For some reason, dune resolves correctly the `unix` library required in `src/core/dune` but not `bytes`. With this PR, the dependencies of that CI setup drop to only OCaml and dune.

Remove the unnecessary dependency on `bytes`

---

.github/workflows/main.yml

`macos-latest` now refers to an M1/ARM64:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
which ocaml.4.08 does not support.
To restore a running CI, this PR thus switches it to the Intel-running macos-13.
(Testing on ARM64 would be nice addition too, but we can address that separately)

Run macOS runners Intel hardware as 4.08.1 does not support M1/ARM64

---

qcheck-core.opam

This upstreams a `qcheck-core` lower bound fixed in opam-repo in https://github.com/ocaml/opam-repository/pull/26169
`test/core/QCheck2_unit_tests.ml` uses `Alcotest.check'` which [was added in 1.2.0](https://github.com/mirage/alcotest/blob/main/CHANGES.md#120-2020-07-13)

Add alcotest lower bound for test-dependency

---

CHANGELOG.md
src/core/QCheck2.ml
src/core/QCheck2.mli

`QCheck.TestResult.t.instances` was originally added in dc53caf to address #51.
With the addition of `QCheck2` it was moved there, `QCheck.TestResult.t` was made abstract, and instead
```ocaml
val QCheck2.TestResult.get_instances : 'a QCheck2.TestResult.t -> 'a list
```
was exposed in the 0.18 interface.
Now https://sherlocode.com/?q=get_instances reveals that noone uses the binding, however #287 reveals that keeping all test inputs causes memory leaks
- that increase with the test count
- that accumulate further as a test list grows.
This PR therefore proposes to remove the list of instances from `TestResult`.
With the PR, on the test case from @esope QCheck2 (and QCheck) regains constant memory usage across increasing test counts - a nice property IMO (beware slight variation below due …

Remove QCheck2.TestResult.get_instances to address memory leak

---

CHANGELOG.md
src/core/QCheck2.ml

QCheck2 fails with compile time warnings:
```ocaml
File "src/core/QCheck2.ml", line 1570, characters 4-33:
1570 |     mutable res: 'a TestResult.t;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 69 [unused-field]: mutable record field res is never mutated.
```
I think this was just an oversight with the refactoring in connection with QCheck2.
The PR removes the warning and the test suite still passes.

Make QCheck2.state.res immutable

---

src/ppx_deriving_qcheck/ppx_deriving_qcheck.ml
test/ppx_deriving_qcheck/deriver/qcheck/test_textual.ml
test/ppx_deriving_qcheck/deriver/qcheck2/dune
test/ppx_deriving_qcheck/deriver/qcheck2/test_mutual.ml

Previously, the code like below was not compiling because 'n' argument was being forgotten. I added a dirty hack of treating all types in mutual block as recursive. Don't know is it a right solution but it seems to help
```ocaml
type tree = Leaf | Node of  tree * tree
and name  = { a: tree }
[@@deriving qcheck2]
```

PPX: mutual recursion with records is now compiling.

---

CHANGELOG.md
src/core/QCheck2.ml

This PR removes an unused field causing an annoying compiler warning:
```
$ dune build
File "src/core/QCheck2.ml", line 1172, characters 2-20:
1172 |   fun_gen: 'b Gen.t; (** How to generate output values *)
^^^^^^^^^^^^^^^^^^
Warning 69 [unused-field]: record field fun_gen is never read.
(However, this field is used to build or mutate values.)
File "src/core/QCheck2.ml", line 1172, characters 2-20:
1172 |   fun_gen: 'b Gen.t; (** How to generate output values *)
^^^^^^^^^^^^^^^^^^
Warning 69 [unused-field]: record field fun_gen is never read.
(However, this field is used to build or mutate values.)
```
Note: The removed code is not visible in the QCheck2 interface and the change is thereby invisible to end-users.
With this PR QCheck now compiles cleanly (silently) on 5.2.
Removing code …

Remove unused field, triggering a compiler warning

---

CHANGELOG.md
example/QCheck_runner_test.expected.ocaml4.32
example/QCheck_runner_test.expected.ocaml4.64
example/QCheck_runner_test.expected.ocaml5.32
example/QCheck_runner_test.expected.ocaml5.64
src/core/QCheck.ml
src/core/QCheck.mli
test/core/QCheck_expect_test.expected.ocaml4.32
test/core/QCheck_expect_test.expected.ocaml4.64
test/core/QCheck_expect_test.expected.ocaml5.32
test/core/QCheck_expect_test.expected.ocaml5.64
test/core/QCheck_unit_tests.ml

This PR adds the missing Shrink.bool combinator and thus fixes #251
Like the QCheck2 bool shrinker it shrinks towards false (for uniformity)

Add Shrink.bool

---

CHANGELOG.md
Makefile
doc/dune
doc/index.mld
src/core/QCheck.ml
src/core/QCheck.mli
src/core/QCheck2.mli

This PR takes a pass over
- [the QCheck module documentation page](https://c-cube.github.io/qcheck/0.22/qcheck-core/QCheck/index.html) and
- [the QCheck2 module documentation page](https://c-cube.github.io/qcheck/0.22/qcheck-core/QCheck/index.html)
The former involves a reorganization for better readability, incl. clarifying the role of `Gen.t` vs `arbitrary`. 
The PR furthermore adds a short `qcheck-core` package documentation page, replacing
https://c-cube.github.io/qcheck/0.22/qcheck-core/index.html to give a brief high-level description of the QCheck/QCheck2 distinction.
Fixes #266 and #281

Documentation polish

---

CHANGELOG.md
example/QCheck_runner_test.expected.ocaml4.32
example/QCheck_runner_test.expected.ocaml4.64
example/QCheck_runner_test.expected.ocaml5.32
example/QCheck_runner_test.expected.ocaml5.64
src/core/QCheck.ml
src/core/QCheck2.ml
test/core/QCheck2_expect_test.expected.ocaml4.32
test/core/QCheck2_expect_test.expected.ocaml4.64
test/core/QCheck2_expect_test.expected.ocaml5.32
test/core/QCheck2_expect_test.expected.ocaml5.64
test/core/QCheck_expect_test.expected.ocaml4.32
test/core/QCheck_expect_test.expected.ocaml4.64
test/core/QCheck_expect_test.expected.ocaml5.32
test/core/QCheck_expect_test.expected.ocaml5.64

As mentioned in #296 
- the `QCheck.Observable.{char,string}` function printers yield unhelpful output, despite using `QCheck.Print.{char,string}`
- quickfixing it like #296, adds another ad-hoc copy, rather than fixing the root cause, namely `QCheck.Observable.{char,string}`
- `QCheck2.Print.{char,string}` already quotes and escapes, creating a `QCheck.Print` / `QCheck2.Print` mismatch for chars and strings
This PR thus suggests the breaking change of fixing `QCheck.Print.{char,string}`.
This further opens up for cleaning up some of the ad-hoc printers in the `arbitrary` combinators (commit d1c1fee)
I'm hoping for fellow QCheck users and developers to chip in to the discussion and share which PR and `QCheck2.Print.{char,string}` they prefer... :pray: :slightly_smiling_face:

Quote and escape in QCheck.Print.{char,string}, aligning it with QCheck2.Print

---

CHANGELOG.md
README.adoc

Fixes #270 
While at it, the PR also elaborates a bit on the installation instructions.

Document `dune` usage in README

---

CHANGELOG.md
src/core/QCheck.ml
src/core/QCheck.mli
src/core/QCheck2.ml
src/core/QCheck2.mli

Fixes #303 
This PR adds `result` combinators to
- `QCheck` as an `arbitrary`
- `QCheck.{Gen,Print,Shrink,Observable}`, and
- `QCheck2.{Gen,Print,Observable}`.
Shrinking-wise they just reduce within `Ok _` and `Error _` without attempting to reduce one to the other.
Edit: 
Ratio-wise, I've gone with 75% in favor of generating `Ok _` - compared to `option`'s 85% preference for `Some _`,
from the rationale that `Ok _` is the preferred and expected path/value, but with a greater chance of `Error _` since its constructor is more expressive than `None` and hence should be exercised more.

Add missing `result` combinators

---

CHANGELOG.md
src/core/QCheck2.ml
test/core/QCheck2_expect_test.expected.ocaml4.32
test/core/QCheck2_expect_test.expected.ocaml4.64
test/core/QCheck2_expect_test.expected.ocaml5.32
test/core/QCheck2_expect_test.expected.ocaml5.64
test/core/QCheck2_tests.ml
test/core/QCheck_expect_test.expected.ocaml4.32
test/core/QCheck_expect_test.expected.ocaml4.64
test/core/QCheck_expect_test.expected.ocaml5.32
test/core/QCheck_expect_test.expected.ocaml5.64
test/core/QCheck_tests.ml

I think I ran into #182, where I want to set `max_fail` to be some value greater than 1.
In my limited sleuthing, I believe the check could have been accidentally removed in https://github.com/c-cube/qcheck/commit/3a9bf2e865665d83c5ed82fc32511f555db2587e#diff-07dbdff6f84a44f565ad4871c5790ad598ceda123f0b8190a711d303d3be28efR1718-R1720 (Hmm, it's highlighted in the link, but it doesn't automatically go to the corresponding line number which is 1767 in file `src/core/QCheck2.ml`). Here, it use to be that if some small parameter and `state.cur_max_fail > 0`, then it would continue otherwise yield. I've just added that latter back in. In the current codebase, it doesn't seem like `cur_max_fail` does anything(4 matches for searching this keyword).
Besides just running this locally and seeing …

Continue on fail when max_fail is gt 0

---

.github/workflows/check-asciidoc.yml
CHANGELOG.md
README.adoc

Prior to opening the PR, I've tested that the workflow indeed fails on the current README.adoc
Fixes #325

Fix asciidoc in README and add a workflow to check it

---

.github/workflows/main.yml

This is the latest and most stable 5.* release after all :slightly_smiling_face:

CI: Build and test on 5.3.0 too - and target Apple silicon macOS

---

.github/workflows/main.yml

This PR adds CI tests on 32-bit i386 of OCaml 4.14 and 5.3 via Docker containers.
Background:
The PRNG changed in OCaml5, meaning outputs differ between 4 and 5, even when run with the same seed.
On top, OCaml supports 32-bit (on OCaml5 only via bytecode). Again, this means different output behaviour between 32-bit and 64-bit, resulting in 4 combinations overall, that QCheck supports.
Our current CI only tests on 64-bit, thus leaving a blind angle.
More than once have I discovered out-of-date 32-bit expect test files during a release to the opam-repo, which tests 32-bit in its CI. This is a bit late to catch something that ideally would come with each PR.
This PR thus offers exactly that: CI testing of 32-bit builds via Docker containers.
I've only added 2 entries - one representative …

Add CI testing on 32-bit i386 of OCaml 4.14 and 5.3 via Docker containers

---

CHANGELOG.md
README.adoc

This PR reworks the frontpage README
- by adding an opam package overview up front
- swaps the installation instructions to suggest `qcheck-core` first
- rewrites the examples to use `qcheck-core` and `QCheck_base_runner`
- adds a `QCheck2` example to showcase integrated shrinking
I also fixed a few typos and added a couple of additional links and explanations.

README updates

---

.github/workflows/check-asciidoc.yml
ppx_deriving_qcheck.opam

The initial CI run in #339 revealed a couple of problems
- the asciidoc checking workflow is missing an `apt-get update`
- the ppx_deriving_qcheck package is missing upper bounds (there's a fix to push them in #331)
This PR takes the first step of getting the CI green again. Afterwards we can take on #339 and lift the bounds with #331.

Make CI green again (sic)

---

CHANGELOG.md
src/runner/QCheck_base_runner.mli

#259 added `QCHECK_MSG_INTERVAL` which is helpful to avoid overflowing CI logs.
However it did not document its existence beyond the CHANGELOG and the source code.
This PR adds the missing documentation to `QCheck_base_runner` and also polishes the existing docs a bit.

Document QCHECK_MSG_INTERVAL

---

CHANGELOG.md
src/core/QCheck.ml
src/core/QCheck.mli
src/core/QCheck2.ml
src/core/QCheck2.mli

While hacking on some `QCheck-STM` tests in ocaml-multicore/multicoretests#547 I found myself missing `QCheck.Gen.map4`. This PR therefore adds `map4` and `map5` combinators to both `QCheck.Gen` and `QCheck2.Gen`,
so that they each support `map`s of arity 1 to 5.

Add `QCheck{,2}.Gen.map{4,5}` combinators

---

CHANGELOG.md
ppx_deriving_qcheck.opam
src/ppx_deriving_qcheck/ppx_deriving_qcheck.ml
test/ppx_deriving_qcheck/deriver/qcheck/test_textual.ml
test/ppx_deriving_qcheck/deriver/qcheck2/test_textual.ml

In preparation for https://github.com/ocaml/opam-repository/pull/27478 there is WIP documentation about the AST bump on the ppxlib wiki: https://github.com/ocaml-ppx/ppxlib/wiki/Upgrading-to-ppxlib-0.36.0

Prepare for 5.2 AST bump

---

CHANGELOG.md
src/runner/QCheck_base_runner.ml
src/runner/QCheck_base_runner.mli

The two other locations in the runner for printing intermediate messages follow a rate-limiting pattern:
https://github.com/c-cube/qcheck/blob/196b9837743a785a7837fcc496bf09ef3950cd69/src/runner/QCheck_base_runner.ml#L277-L284
https://github.com/c-cube/qcheck/blob/196b9837743a785a7837fcc496bf09ef3950cd69/src/runner/QCheck_base_runner.ml#L297-L302
But not at 
https://github.com/c-cube/qcheck/blob/196b9837743a785a7837fcc496bf09ef3950cd69/src/runner/QCheck_base_runner.ml#L418-L421

Start message timing from unconditional first print

---

CHANGELOG.md
src/core/QCheck2.ml
test/core/QCheck2_expect_test.expected.ocaml4.32
test/core/QCheck2_expect_test.expected.ocaml4.64
test/core/QCheck2_expect_test.expected.ocaml5.32
test/core/QCheck2_expect_test.expected.ocaml5.64
test/core/QCheck2_tests.ml
test/core/QCheck_expect_test.expected.ocaml4.32
test/core/QCheck_expect_test.expected.ocaml4.64
test/core/QCheck_expect_test.expected.ocaml5.32
test/core/QCheck_expect_test.expected.ocaml5.64
test/core/QCheck_tests.ml

Example crash fixed:
> # QCheck_base_runner.run_tests [QCheck2.Test.make ~count:100000 ~print:QCheck2.Print.float (QCheck2.Gen.float_range (-2.) (-1.)) (fun _ -> false)];;
> random seed: 143173129
> Exception:
> Invalid_argument
>  "Gen.float_bound_inclusive: origin value -1. is lower than low value 0.".
I also think we could generate `float_range` to avoid the range limit currently baked in.
I don't know a good way to generate the other expected files for alternative platforms.

Fix QCheck2 float_range operator with negative bounds

---

CHANGELOG.md
src/core/QCheck.mli

Fixes #219
This documents the `QCheck.Shrink` invariants both in the documentation's `QCheck` front page and in the `Shrink` sub-page.
Strictly speaking, returning the identity is a special case of not meeting a strictly decreasing termination measure.
As a QCheck shrinker author, it is however a common enough error I've also made myself, so I believe it is worth warning explicitly about.

Document QCheck.Shrink invariants

---

CHANGELOG.md
README.adoc

Fixes #186
PR #302 added a note about the `QCheck`/`QCheck2` situation to the `qcheck-core` documentation page.
This little PR adds a similar note to the front page README.
Together the two PRs document the situation for newcomers and occasional contributors as requested in #186.

Elaborate on QCheck/QCheck2 situation in README too

---

CHANGELOG.md
example/QCheck_runner_test.expected.ocaml4.32
example/QCheck_runner_test.expected.ocaml4.64
example/QCheck_runner_test.expected.ocaml5.32
example/QCheck_runner_test.expected.ocaml5.64
src/core/QCheck2.ml
src/runner/QCheck_base_runner.mli
test/core/QCheck2_expect_test.expected.ocaml4.32
test/core/QCheck2_expect_test.expected.ocaml4.64
test/core/QCheck2_expect_test.expected.ocaml5.32
test/core/QCheck2_expect_test.expected.ocaml5.64
test/core/QCheck2_tests.ml
test/core/QCheck_expect_test.expected.ocaml4.32
test/core/QCheck_expect_test.expected.ocaml4.64
test/core/QCheck_expect_test.expected.ocaml5.32
test/core/QCheck_expect_test.expected.ocaml5.64
test/core/QCheck_tests.ml

The `collect` statistics are nice for grouping things by `string`s, however without manually adding spaces to align them they appear sub-optimal:
```
Collect results for test option dist:
None: 1519 cases
Some _: 8481 cases
```
This PR aligns the printed labels and counts under each other, and throws a quick percentage in on top: 
```
Collect results for test option dist:
None:     1519 cases (15.2%)
Some _:   8481 cases (84.8%)
```
Overall this results in a nicer `collect` stats output :slightly_smiling_face: :sparkles:

Align printed `collect` statistics

---

ppx_deriving_qcheck.opam

Spotted on the rendered version at https://opam.ocaml.org/packages/ppx_deriving_qcheck/

Fix 404 bug-reports link in ppx_deriving_qcheck.opam
